apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond-config
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: bond0
        description: Active-backup bond
        type: bond
        state: up
        ipv4:
          enabled: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: "100"
          port:
            - ens224
            - ens256
