apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: vm-layer2-network
  namespace: vm-guests
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "192.168.100.0/24"
    mtu: 1400
    ipamLifecycle: Persistent
