apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan100
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "bridge-vlan100",
      "type": "cnv-bridge",
      "bridge": "br-vlan100",
      "macspoofchk": true,
      "ipam": {}
    }
