apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-static-ipam
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "localnet-static",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/localnet-static-ipam",
      "subnets": "192.168.100.0/24",
      "excludeSubnets": "192.168.100.1-192.168.100.50",
      "ipam": {
        "type": "static"
      }
    }
