apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-vlan-100
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "localnet-vlan-100",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/localnet-vlan-100",
      "vlanID": 100,
      "subnets": "192.168.100.0/24",
      "excludeSubnets": "192.168.100.1/32"
    }
