apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-native
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "localnet-native",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/localnet-native",
      "subnets": "192.168.1.0/24",
      "excludeSubnets": "192.168.1.1/32"
    }
