apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: overlay-dhcp
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "overlay-dhcp",
      "type": "ovn-k8s-cni-overlay",
      "topology": "layer2",
      "subnets": "10.200.0.0/16",
      "mtu": 1400,
      "netAttachDefName": "default/overlay-dhcp",
      "ipam": {
        "type": "ovn-k8s-cni-ipam",
        "provider": "ovn-kubernetes"
      }
    }
