apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-with-data-disk
  namespace: vms-prod
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-with-data-disk-root
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 40Gi
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-with-data-disk-data
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 100Gi
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9-with-data-disk
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: datadisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 16Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: rhel9-with-data-disk-root
          name: rootdisk
        - dataVolume:
            name: rhel9-with-data-disk-data
          name: datadisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: changeme
              chpasswd: { expire: True }
              ssh_pwauth: True
          name: cloudinitdisk
