apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-vms
  namespace: vms-prod
spec:
  podSelector:
    matchLabels:
      kubevirt.io/domain: ""
  policyTypes:
    - Ingress
  ingress:
    - {}
