apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-operators-binding
  namespace: vms-prod
subjects:
  - kind: User
    name: alice@example.com
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: vm-operators
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: vm-operator
  apiGroup: rbac.authorization.k8s.io
