apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-manager
  namespace: vms-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-manager-binding
  namespace: vms-prod
subjects:
  - kind: ServiceAccount
    name: vm-manager
    namespace: vms-prod
roleRef:
  kind: Role
  name: vm-operator
  apiGroup: rbac.authorization.k8s.io
