apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9-dv
  namespace: vms-prod
spec:
  source:
    http:
      url: https://example.com/rhel9.qcow2
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
    storageClassName: lvms-vg1
