apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm-disk-clone
  namespace: vms-prod
spec:
  source:
    pvc:
      namespace: vms-prod
      name: original-vm-disk
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: lvms-vg1
