apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-dv
  namespace: vms-prod
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/fedora:latest
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: lvms-vg1
